---
name: TorrServer AutoUpdate
slug: torrserver
description: TorrServer for Home Assistant with automatic upstream release updates
version: 144.1.9
url: https://github.com/menfis911/hassio-TS-autoupdate
changelog: https://github.com/menfis911/hassio-TS-autoupdate/blob/main/torrserver/CHANGELOG.md
init: false
auth_api: true
arch:
  - amd64
  - aarch64
image: ghcr.io/menfis911/hassio-ts-autoupdate
map:
  - addon_config:rw
services:
  - mqtt:want
options:
  port: 8090
  httpauth: false
  logins:
    - username: homeassistant
      password: homeassistant
  tgtoken: ""
  m3u_custom_host: ""
  ssl: false
  ssl_port: 8091
  ssl_cert: ""
  ssl_key: ""
  proxymode: disabled
  proxyurl: ""
  weblog: false
  mqtt_discovery: true
schema:
  port: "int(1024,49151)"
  httpauth: bool
  logins:
    - username: str
      password: str
  tgtoken: "str?"
  m3u_custom_host: "str?"
  ssl: bool
  ssl_port: "int(1024,49151)"
  ssl_cert: "str?"
  ssl_key: "str?"
  proxymode: "list(disabled|tracker|peers|full)"
  proxyurl: "str?"
  weblog: bool
  mqtt_discovery: bool
webui: "http://[HOST]:[PORT:8090]/"
ingress: true
ingress_port: 8090
ingress_entry: ui
ingress_stream: true
host_network: true
watchdog: "http://[HOST]:[PORT:8090]/echo"
startup: system
panel_icon: mdi:movie-open-play
panel_title: TorrServer
